#!/usr/bin/env bash

ws=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)

if [ -z $2 ]
then
    case "$1" in
        firefox)
            i3-msg workspace 2, exec firefox, workspace $ws
            ;;
        code)
            i3-msg workspace 3, exec code, workspace $ws
            ;;
        pcmanfm)
            i3-msg workspace 4, exec pcmanfm, workspace $ws
            ;;
        thunar)
            i3-msg workspace 4, exec thunar, workspace $ws
            ;;
        lutris)
            i3-msg workspace 5, exec lutris, workspace $ws
            ;;
        discord)
            i3-msg workspace 9, exec discord, workspace $ws
            ;;
        thunderbird)
            i3-msg workspace 10, exec thunderbird, workspace $ws
            ;;
    esac

    exit 
fi

i3-msg workspace $2, exec $1, workspace $ws